/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 venus.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/venus.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Atmosphere.geometry} material={materials.Atmosphere} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Venus.geometry} material={materials.Venus} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/venus.glb')
