import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useSelector } from "react-redux";
import HomePage from "@/features/Home";
import Portfolio from "../features/Home/Portfolio";
import Skils from "../components/SKils";
export default function Home() {
  const counter = useSelector((state) => state);

  console.log(counter);
  return (
    <>
      <Head>
        <title>Boxmedia | Leonardo Costa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HomePage />
        <Portfolio />
        <Skils />
      </main>
    </>
  );
}
